# 线上配置文件
# @author <a href="https://github.com/ricejson">程序员米饭</a>
# @from <a href="https://ricejson.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  session:
    redis:
      configure-action: none
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbconn.sealoshzh.site:48143/mianshi
    username: root
    password: 8n6b4zr9
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_db
#    username: root
#    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 62.234.138.98
    port: 6379
    timeout: 5000
    password: ~RICEjson666
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://62.234.138.98:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
nacos:
  config:
    data-id: "mianshi"
    group: "DEFAULT_GROUP"
    server-addr: "62.234.138.98:8848"
# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: mianshi
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  cookie:
    path: /           # ← 关键！改为根路径
    same-site: none
    secure: true      # ← 必须加！


